### ISSUE TITLE
国服更新后没法用了。

### ISSUE THREAD

**Issue by linshouwen** [cangzhang/champ-r#251]
国服更新后没法用了，弹不出界面。

**Comment by WMEEMW** [comment]
确实是这样了

**Comment by fatesealed** [comment]
确实是这样了

**Comment by starolala** [comment]
是的，我还调了好几次测试服

**Comment by zpltren** [comment]
是的，更新13.3以后就不会弹窗了。。

**Comment by WangPei-hitman** [comment]
正确的

**Comment by Polaris-Yi** [comment]
是的，我还在网上到处找插件，Blitz也是时灵时不灵

**Comment by Java-S12138** [comment]
Frank项目中, 有人提供一个解决方案, 大家可以试试

 " 我发现了一个解决方式：需要修改lol/TCLS目录下的wegame_launch.tmp文件LastLoginMethod=2改成LastLoginMethod=1，然后关闭WeGame，直接启动TCLS目录下的Client.exe。 " [原文链接](https://github.com/Java-S12138/frank/issues/110)

**Comment by WMEEMW** [comment]
我看了下，原本就是LastLoginMethod=1


| |
王蒙恩
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年2月22日 11:15 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [cangzhang/champ-r] 国服更新后没法用了。 (Issue #251) |

Frank项目中, 有人提供一个解决方案, 大家可以试试

" 我发现了一个解决方式：需要修改lol/TCLS目录下的wegame_launch.tmp文件LastLoginMethod=2改成LastLoginMethod=1，然后关闭WeGame，直接启动TCLS目录下的Client.exe。 " 原文链接

**Comment by svenliu117** [comment]
看来我并不是一个人遇到这个问题。。。还以为是重装系统的问题。

**Comment by svenliu117** [comment]
> 我看了下，原本就是LastLoginMethod=1 | | 王蒙恩 | | ***@***.*** | ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2023年2月22日 11:15 | | 收件人 | ***@***.***> | | 抄送人 | ***@***.***> , ***@***.***> | | 主题 | Re: [cangzhang/champ-r] 国服更新后没法用了。 (Issue #251) | Frank项目中, 有人提供一个解决方案, 大家可以试试 " 我发现了一个解决方式：需要修改lol/TCLS目录下的wegame_launch.tmp文件LastLoginMethod=2改成LastLoginMethod=1，然后关闭WeGame，直接启动TCLS目录下的Client.exe。 " 原文链接 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

此方法无效，我的文件本来就=1，关闭Wegame, 启动Client.exe 依然无法弹窗。应该是客户端的问题，暂时无解。

**Comment by WMEEMW** [comment]
暂时就手点吧，也没啥好办法了


| |
王蒙恩
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年2月24日 17:51 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [cangzhang/champ-r] 国服更新后没法用了。 (Issue #251) |

我看了下，原本就是LastLoginMethod=1 | | 王蒙恩 | | @.*** | ---- 回复的原邮件 ---- | 发件人 | @.> | | 发送日期 | 2023年2月22日 11:15 | | 收件人 | @.> | | 抄送人 | @.> , @.> | | 主题 | Re: [cangzhang/champ-r] 国服更新后没法用了。 (Issue #251) | Frank项目中, 有人提供一个解决方案, 大家可以试试 " 我发现了一个解决方式：需要修改lol/TCLS目录下的wegame_launch.tmp文件LastLoginMethod=2改成LastLoginMethod=1，然后关闭WeGame，直接启动TCLS目录下的Client.exe。 " 原文链接 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***>

此方法无效，我的文件本来就=1，关闭Wegame, 启动Client.exe 依然无法弹窗。应该是客户端的问题，暂时无解。

**Comment by xxbash** [comment]
原来大家都有这个问题，我以为是我有台服程序的原因，我台服就正常用，国服就是不行

**Comment by cangzhang** [comment]
大家試試 https://github.com/cangzhang/champ-r/releases/tag/v2.0.0
如果有問題請繼續反饋
